<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.javeriana.edu.co/co/schemas/process/bpm/ConsultarPrototipoRecomendaciones/v1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/WS_ConsProtRecomendaciones" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/app_eaes_soaint/SOA_Database_2/WS_ConsProtRecomendaciones"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://xmlns.oracle.com/app_eaes_soaint/SOA_Database_2/bpel_consprotrecomendaciones">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/WS_ConsProtRecomendaciones.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/WS_ConsProtRecomendaciones"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpel_consprotrecomendaciones.wsdl"/>
            <oracle-xsl-mapper:rootElement name="response" namespace="http://xmlns.javeriana.edu.co/co/schemas/process/bpm/ConsultarPrototipoRecomendaciones/v1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [SAT APR 04 09:09:20 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:response>
         <tns:prototipo>
            <tns:codigoPrototipo>
               <xsl:value-of select="/ns0:OutputParameters/ns0:V_TYPE_PROTOTIPO/ns0:ID_PROTOTIPO"/>
            </tns:codigoPrototipo>
            <tns:titulo>
               <xsl:value-of select="/ns0:OutputParameters/ns0:V_TYPE_PROTOTIPO/ns0:TITULO"/>
            </tns:titulo>
            <tns:fechaInicio>
               <xsl:value-of select="/ns0:OutputParameters/ns0:V_TYPE_PROTOTIPO/ns0:FECHA_INICIO"/>
            </tns:fechaInicio>
            <tns:fechaCierre>
               <xsl:value-of select="/ns0:OutputParameters/ns0:V_TYPE_PROTOTIPO/ns0:FECHA_CIERRE"/>
            </tns:fechaCierre>
            <tns:detalle>
               <xsl:value-of select="/ns0:OutputParameters/ns0:V_TYPE_PROTOTIPO/ns0:DETALLE"/>
            </tns:detalle>
            <tns:estado>
               <xsl:value-of select="/ns0:OutputParameters/ns0:V_TYPE_PROTOTIPO/ns0:ESTADO"/>
            </tns:estado>
            <tns:presupuesto>
               <xsl:value-of select="/ns0:OutputParameters/ns0:V_TYPE_PROTOTIPO/ns0:PRESUPUEST"/>
            </tns:presupuesto>
            <tns:tipo>
               <xsl:value-of select="/ns0:OutputParameters/ns0:V_TYPE_PROTOTIPO/ns0:TIPO"/>
            </tns:tipo>
            <tns:conocimientos>
               <xsl:value-of select="/ns0:OutputParameters/ns0:V_TYPE_PROTOTIPO/ns0:CONOCIMIENTOS"/>
            </tns:conocimientos>
         </tns:prototipo>
         <xsl:if test="count (/ns0:OutputParameters/ns0:V_ARRAY_RECOMENDACIONES_TYPE/ns0:V_ARRAY_RECOMENDACIONES_TYPE_ITEM ) > 0">
            <xsl:for-each select="/ns0:OutputParameters/ns0:V_ARRAY_RECOMENDACIONES_TYPE/ns0:V_ARRAY_RECOMENDACIONES_TYPE_ITEM">
               <tns:recomendaciones>
                  <tns:codigoPrototipo>
                     <xsl:value-of select="ns0:ID_PROTOTIPO"/>
                  </tns:codigoPrototipo>
                  <tns:observacion>
                     <xsl:value-of select="ns0:OBSERVACION"/>
                  </tns:observacion>
               </tns:recomendaciones>
            </xsl:for-each>
         </xsl:if>
      </tns:response>
   </xsl:template>
</xsl:stylesheet>
