
package co.edu.javeriana.proxies.consultarcandidatos.proxy;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "bpel_consultacandidatos_client_ep",
                  targetNamespace = "http://xmlns.oracle.com/app_eaes_soaint/SOA_Database_2/bpel_consultacandidatos",
                  wsdlLocation =
                  "http://bpm-dv1:7003/soa-infra/services/default/SOA_Database_2/bpel_consultacandidatos_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fapp_eaes_soaint%2FSOA_Database_2%2Fbpel_consultacandidatos%7Dbpel_consultacandidatos_client_ep")
@HandlerChain(file="Bpel_consultacandidatos_client_epProxy-HandlerChain.xml")
public class BpelConsultacandidatosClientEp extends Service {

    private final static URL BPELCONSULTACANDIDATOSCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException BPELCONSULTACANDIDATOSCLIENTEP_EXCEPTION;
    private final static QName BPELCONSULTACANDIDATOSCLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Database_2/bpel_consultacandidatos",
                  "bpel_consultacandidatos_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://bpm-dv1:7003/soa-infra/services/default/SOA_Database_2/bpel_consultacandidatos_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fapp_eaes_soaint%2FSOA_Database_2%2Fbpel_consultacandidatos%7Dbpel_consultacandidatos_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BPELCONSULTACANDIDATOSCLIENTEP_WSDL_LOCATION = url;
        BPELCONSULTACANDIDATOSCLIENTEP_EXCEPTION = e;
    }

    public BpelConsultacandidatosClientEp() {
        super(__getWsdlLocation(), BPELCONSULTACANDIDATOSCLIENTEP_QNAME);
    }

    public BpelConsultacandidatosClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), BPELCONSULTACANDIDATOSCLIENTEP_QNAME, features);
    }

    public BpelConsultacandidatosClientEp(URL wsdlLocation) {
        super(wsdlLocation, BPELCONSULTACANDIDATOSCLIENTEP_QNAME);
    }

    public BpelConsultacandidatosClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BPELCONSULTACANDIDATOSCLIENTEP_QNAME, features);
    }

    public BpelConsultacandidatosClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BpelConsultacandidatosClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BpelConsultacandidatos
     */
    @WebEndpoint(name = "bpel_consultacandidatos_pt")
    public BpelConsultacandidatos getBpelConsultacandidatosPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Database_2/bpel_consultacandidatos",
                                       "bpel_consultacandidatos_pt"), BpelConsultacandidatos.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BpelConsultacandidatos
     */
    @WebEndpoint(name = "bpel_consultacandidatos_pt")
    public BpelConsultacandidatos getBpelConsultacandidatosPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Database_2/bpel_consultacandidatos",
                                       "bpel_consultacandidatos_pt"), BpelConsultacandidatos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BPELCONSULTACANDIDATOSCLIENTEP_EXCEPTION != null) {
            throw BPELCONSULTACANDIDATOSCLIENTEP_EXCEPTION;
        }
        return BPELCONSULTACANDIDATOSCLIENTEP_WSDL_LOCATION;
    }

}
