<wsdl:definitions
     name="WS_InsertarColaborador"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/app_eaes_soaint/SOA_Database/WS_InsertarColaborador"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/app_eaes_soaint/SOA_Database/WS_InsertarColaborador"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/WS_InsertarColaborador"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="WS_InsertarColaborador_plt" >
    <plt:role name="WS_InsertarColaborador_role" >
      <plt:portType name="tns:WS_InsertarColaborador_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/WS_InsertarColaborador"
               schemaLocation="oramds:/apps/resources/SOA/SCHEMAs/WS_InsertarColaborador_sp.xsd" />
     </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:portType name="WS_InsertarColaborador_ptt">
        <wsdl:operation name="WS_InsertarColaborador">
            <wsdl:input message="tns:args_in_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
