
package co.edu.javeriana.proxies.consultarrecomendaciones.proxy;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "bpel_consprotrecomendaciones_client_ep",
                  targetNamespace =
                  "http://xmlns.oracle.com/app_eaes_soaint/SOA_Database_2/bpel_consprotrecomendaciones",
                  wsdlLocation =
                  "http://bpm-dv1:7003/soa-infra/services/default/SOA_Database_2/bpel_consprotrecomendaciones_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fapp_eaes_soaint%2FSOA_Database_2%2Fbpel_consprotrecomendaciones%7Dbpel_consprotrecomendaciones_client_ep")
@HandlerChain(file="Bpel_consprotrecomendaciones_client_epProxy-HandlerChain.xml")
public class BpelConsprotrecomendacionesClientEp extends Service {

    private final static URL BPELCONSPROTRECOMENDACIONESCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException BPELCONSPROTRECOMENDACIONESCLIENTEP_EXCEPTION;
    private final static QName BPELCONSPROTRECOMENDACIONESCLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Database_2/bpel_consprotrecomendaciones",
                  "bpel_consprotrecomendaciones_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://bpm-dv1:7003/soa-infra/services/default/SOA_Database_2/bpel_consprotrecomendaciones_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fapp_eaes_soaint%2FSOA_Database_2%2Fbpel_consprotrecomendaciones%7Dbpel_consprotrecomendaciones_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BPELCONSPROTRECOMENDACIONESCLIENTEP_WSDL_LOCATION = url;
        BPELCONSPROTRECOMENDACIONESCLIENTEP_EXCEPTION = e;
    }

    public BpelConsprotrecomendacionesClientEp() {
        super(__getWsdlLocation(), BPELCONSPROTRECOMENDACIONESCLIENTEP_QNAME);
    }

    public BpelConsprotrecomendacionesClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), BPELCONSPROTRECOMENDACIONESCLIENTEP_QNAME, features);
    }

    public BpelConsprotrecomendacionesClientEp(URL wsdlLocation) {
        super(wsdlLocation, BPELCONSPROTRECOMENDACIONESCLIENTEP_QNAME);
    }

    public BpelConsprotrecomendacionesClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BPELCONSPROTRECOMENDACIONESCLIENTEP_QNAME, features);
    }

    public BpelConsprotrecomendacionesClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BpelConsprotrecomendacionesClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BpelConsprotrecomendaciones
     */
    @WebEndpoint(name = "bpel_consprotrecomendaciones_pt")
    public BpelConsprotrecomendaciones getBpelConsprotrecomendacionesPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Database_2/bpel_consprotrecomendaciones",
                                       "bpel_consprotrecomendaciones_pt"), BpelConsprotrecomendaciones.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BpelConsprotrecomendaciones
     */
    @WebEndpoint(name = "bpel_consprotrecomendaciones_pt")
    public BpelConsprotrecomendaciones getBpelConsprotrecomendacionesPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Database_2/bpel_consprotrecomendaciones",
                                       "bpel_consprotrecomendaciones_pt"), BpelConsprotrecomendaciones.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BPELCONSPROTRECOMENDACIONESCLIENTEP_EXCEPTION != null) {
            throw BPELCONSPROTRECOMENDACIONESCLIENTEP_EXCEPTION;
        }
        return BPELCONSPROTRECOMENDACIONESCLIENTEP_WSDL_LOCATION;
    }

}
