package co.edu.javeriana.proxies.consultarrecomendaciones.proxy;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914
public class bpel_consprotrecomendaciones_ptClient {
    public static void main(String[] args) {
        BpelConsprotrecomendacionesClientEp bpelConsprotrecomendacionesClientEp =
            new BpelConsprotrecomendacionesClientEp();
        BpelConsprotrecomendaciones bpelConsprotrecomendaciones =
            bpelConsprotrecomendacionesClientEp.getBpelConsprotrecomendacionesPt();
        // Add your code to call the desired methods.


    }
}
