<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://xmlns.javeriana.edu.co/co/schemas/process/bpm/InsertarPrototipo/v1.0" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/WS_InsPrototipo" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://xmlns.oracle.com/app_eaes_soaint/SOA_Database/bpel_insertarprototipo"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/app_eaes_soaint/SOA_Database/WS_InsPrototipo"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpel_insertarprototipo.wsdl"/>
            <oracle-xsl-mapper:rootElement name="request" namespace="http://xmlns.javeriana.edu.co/co/schemas/process/bpm/InsertarPrototipo/v1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/WS_InsPrototipo.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/WS_InsPrototipo"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [THU APR 02 22:27:09 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:InputParameters>
         <tns:V_TITULO>
            <xsl:value-of select="/ns0:request/ns0:titulo"/>
         </tns:V_TITULO>
         <tns:V_FECHA_INICIO>
            <xsl:value-of select="/ns0:request/ns0:fechaInicio"/>
         </tns:V_FECHA_INICIO>
         <tns:V_FECHA_CIERRE>
            <xsl:value-of select="/ns0:request/ns0:fechaFin"/>
         </tns:V_FECHA_CIERRE>
         <tns:V_DETALLE>
            <xsl:value-of select="/ns0:request/ns0:detalle"/>
         </tns:V_DETALLE>
         <tns:V_ESTADO>
            <xsl:value-of select="/ns0:request/ns0:estado"/>
         </tns:V_ESTADO>
         <tns:V_PRESUPUESTO>
            <xsl:value-of select="/ns0:request/ns0:presupuesto"/>
         </tns:V_PRESUPUESTO>
         <tns:V_TIPO>
            <xsl:value-of select="/ns0:request/ns0:tipo"/>
         </tns:V_TIPO>
         <tns:V_CONOCIMIENTOS>
            <xsl:value-of select="/ns0:request/ns0:conocimientos"/>
         </tns:V_CONOCIMIENTOS>
         <tns:V_ARRAY_RECOMENDACIONES_TYPE>
            <xsl:if test="count (/ns0:request/ns0:recomendaciones/ns0:listaRecomendaciones ) > 0">
               <xsl:for-each select="/ns0:request/ns0:recomendaciones/ns0:listaRecomendaciones">
                  <tns:V_ARRAY_RECOMENDACIONES_TYPE_ITEM>
                     <tns:ID_PROTOTIPO>
                        <xsl:value-of select="ns0:codigoPrototipo"/>
                     </tns:ID_PROTOTIPO>
                     <tns:OBSERVACION>
                        <xsl:value-of select="ns0:observacion"/>
                     </tns:OBSERVACION>
                  </tns:V_ARRAY_RECOMENDACIONES_TYPE_ITEM>
               </xsl:for-each>
            </xsl:if>
         </tns:V_ARRAY_RECOMENDACIONES_TYPE>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>
