<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://xmlns.javeriana.edu.co/co/schemas/process/bpm/InsertarColaborador/v1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/WS_InsertarColaborador" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://xmlns.oracle.com/app_eaes_soaint/SOA_Database/bpel_inscolaborador"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/app_eaes_soaint/SOA_Database/WS_InsertarColaborador"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpel_inscolaborador.wsdl"/>
            <oracle-xsl-mapper:rootElement name="request" namespace="http://xmlns.javeriana.edu.co/co/schemas/process/bpm/InsertarColaborador/v1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/WS_InsertarColaborador.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/WS_InsertarColaborador"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [FRI APR 03 01:17:20 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:InputParameters>
         <tns:V_ID_ROL>
            <xsl:value-of select="/ns0:request/ns0:codigoRol"/>
         </tns:V_ID_ROL>
         <tns:V_PRIMER_NOMBRE>
            <xsl:value-of select="/ns0:request/ns0:primerNombre"/>
         </tns:V_PRIMER_NOMBRE>
         <tns:V_SEGUNDO_NOMBRE>
            <xsl:value-of select="/ns0:request/ns0:segundoNombre"/>
         </tns:V_SEGUNDO_NOMBRE>
         <tns:V_PRIMER_APELLIDO>
            <xsl:value-of select="/ns0:request/ns0:primerApellido"/>
         </tns:V_PRIMER_APELLIDO>
         <tns:V_SEGUNDO_APELLIDO>
            <xsl:value-of select="/ns0:request/ns0:segundoApellido"/>
         </tns:V_SEGUNDO_APELLIDO>
         <tns:V_EMAIL>
            <xsl:value-of select="/ns0:request/ns0:correoElectronica"/>
         </tns:V_EMAIL>
         <tns:V_TELEFONO>
            <xsl:value-of select="/ns0:request/ns0:telefono"/>
         </tns:V_TELEFONO>
         <tns:V_DISPONIBLE>
            <xsl:value-of select="/ns0:request/ns0:disponible"/>
         </tns:V_DISPONIBLE>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>
