
package co.edu.javeriana.proxies.consultardocumento.proxy;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "bpel_consultardocumento_client_ep",
                  targetNamespace = "http://xmlns.oracle.com/app_eaes_soaint/SOA_Database/bpel_consultardocumento",
                  wsdlLocation =
                  "http://bpm-dv1:7003/soa-infra/services/default/SOA_Database/bpel_consultardocumento_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fapp_eaes_soaint%2FSOA_Database%2Fbpel_consultardocumento%7Dbpel_consultardocumento_client_ep")
@HandlerChain(file="Bpel_consultardocumento_client_epProxy-HandlerChain.xml")
public class BpelConsultardocumentoClientEp extends Service {

    private final static URL BPELCONSULTARDOCUMENTOCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException BPELCONSULTARDOCUMENTOCLIENTEP_EXCEPTION;
    private final static QName BPELCONSULTARDOCUMENTOCLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Database/bpel_consultardocumento",
                  "bpel_consultardocumento_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://bpm-dv1:7003/soa-infra/services/default/SOA_Database/bpel_consultardocumento_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fapp_eaes_soaint%2FSOA_Database%2Fbpel_consultardocumento%7Dbpel_consultardocumento_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BPELCONSULTARDOCUMENTOCLIENTEP_WSDL_LOCATION = url;
        BPELCONSULTARDOCUMENTOCLIENTEP_EXCEPTION = e;
    }

    public BpelConsultardocumentoClientEp() {
        super(__getWsdlLocation(), BPELCONSULTARDOCUMENTOCLIENTEP_QNAME);
    }

    public BpelConsultardocumentoClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), BPELCONSULTARDOCUMENTOCLIENTEP_QNAME, features);
    }

    public BpelConsultardocumentoClientEp(URL wsdlLocation) {
        super(wsdlLocation, BPELCONSULTARDOCUMENTOCLIENTEP_QNAME);
    }

    public BpelConsultardocumentoClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BPELCONSULTARDOCUMENTOCLIENTEP_QNAME, features);
    }

    public BpelConsultardocumentoClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BpelConsultardocumentoClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BpelConsultardocumento
     */
    @WebEndpoint(name = "bpel_consultardocumento_pt")
    public BpelConsultardocumento getBpelConsultardocumentoPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Database/bpel_consultardocumento",
                                       "bpel_consultardocumento_pt"), BpelConsultardocumento.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BpelConsultardocumento
     */
    @WebEndpoint(name = "bpel_consultardocumento_pt")
    public BpelConsultardocumento getBpelConsultardocumentoPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Database/bpel_consultardocumento",
                                       "bpel_consultardocumento_pt"), BpelConsultardocumento.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BPELCONSULTARDOCUMENTOCLIENTEP_EXCEPTION != null) {
            throw BPELCONSULTARDOCUMENTOCLIENTEP_EXCEPTION;
        }
        return BPELCONSULTARDOCUMENTOCLIENTEP_WSDL_LOCATION;
    }

}
