
package co.edu.javeriana.proxies.checkin.proxy;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "bpel_checkin_wcc_client_ep",
                  targetNamespace = "http://xmlns.oracle.com/app_eaes_soaint/SOA_Content/bpel_checkin_wcc",
                  wsdlLocation =
                  "http://bpm-dv1:7003/soa-infra/services/default/SOA_Content/bpel_checkin_wcc_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fapp_eaes_soaint%2FSOA_Content%2Fbpel_checkin_wcc%7Dbpel_checkin_wcc_client_ep")
@HandlerChain(file="Bpel_checkin_wcc_client_epProxy-HandlerChain.xml")
public class BpelCheckinWccClientEp extends Service {

    private final static URL BPELCHECKINWCCCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException BPELCHECKINWCCCLIENTEP_EXCEPTION;
    private final static QName BPELCHECKINWCCCLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Content/bpel_checkin_wcc", "bpel_checkin_wcc_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://bpm-dv1:7003/soa-infra/services/default/SOA_Content/bpel_checkin_wcc_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fapp_eaes_soaint%2FSOA_Content%2Fbpel_checkin_wcc%7Dbpel_checkin_wcc_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BPELCHECKINWCCCLIENTEP_WSDL_LOCATION = url;
        BPELCHECKINWCCCLIENTEP_EXCEPTION = e;
    }

    public BpelCheckinWccClientEp() {
        super(__getWsdlLocation(), BPELCHECKINWCCCLIENTEP_QNAME);
    }

    public BpelCheckinWccClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), BPELCHECKINWCCCLIENTEP_QNAME, features);
    }

    public BpelCheckinWccClientEp(URL wsdlLocation) {
        super(wsdlLocation, BPELCHECKINWCCCLIENTEP_QNAME);
    }

    public BpelCheckinWccClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BPELCHECKINWCCCLIENTEP_QNAME, features);
    }

    public BpelCheckinWccClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BpelCheckinWccClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BpelCheckinWcc
     */
    @WebEndpoint(name = "bpel_checkin_wcc_pt")
    public BpelCheckinWcc getBpelCheckinWccPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Content/bpel_checkin_wcc",
                                       "bpel_checkin_wcc_pt"), BpelCheckinWcc.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BpelCheckinWcc
     */
    @WebEndpoint(name = "bpel_checkin_wcc_pt")
    public BpelCheckinWcc getBpelCheckinWccPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Content/bpel_checkin_wcc",
                                       "bpel_checkin_wcc_pt"), BpelCheckinWcc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BPELCHECKINWCCCLIENTEP_EXCEPTION != null) {
            throw BPELCHECKINWCCCLIENTEP_EXCEPTION;
        }
        return BPELCHECKINWCCCLIENTEP_WSDL_LOCATION;
    }

}
