
package co.edu.javeriana.proxies.advancesearch.proxy;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "bpel_advancesearch_client_ep",
                  targetNamespace = "http://xmlns.oracle.com/app_eaes_soaint/SOA_Content/bpel_AdvanceSearch",
                  wsdlLocation =
                  "http://bpm-dv1:7003/soa-infra/services/default/SOA_Content/bpel_advancesearch_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fapp_eaes_soaint%2FSOA_Content%2Fbpel_AdvanceSearch%7Dbpel_advancesearch_client_ep")
public class BpelAdvancesearchClientEp extends Service {

    private final static URL BPELADVANCESEARCHCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException BPELADVANCESEARCHCLIENTEP_EXCEPTION;
    private final static QName BPELADVANCESEARCHCLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Content/bpel_AdvanceSearch",
                  "bpel_advancesearch_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://bpm-dv1:7003/soa-infra/services/default/SOA_Content/bpel_advancesearch_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fapp_eaes_soaint%2FSOA_Content%2Fbpel_AdvanceSearch%7Dbpel_advancesearch_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BPELADVANCESEARCHCLIENTEP_WSDL_LOCATION = url;
        BPELADVANCESEARCHCLIENTEP_EXCEPTION = e;
    }

    public BpelAdvancesearchClientEp() {
        super(__getWsdlLocation(), BPELADVANCESEARCHCLIENTEP_QNAME);
    }

    public BpelAdvancesearchClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), BPELADVANCESEARCHCLIENTEP_QNAME, features);
    }

    public BpelAdvancesearchClientEp(URL wsdlLocation) {
        super(wsdlLocation, BPELADVANCESEARCHCLIENTEP_QNAME);
    }

    public BpelAdvancesearchClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BPELADVANCESEARCHCLIENTEP_QNAME, features);
    }

    public BpelAdvancesearchClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BpelAdvancesearchClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BpelAdvanceSearch
     */
    @WebEndpoint(name = "bpel_AdvanceSearch_pt")
    public BpelAdvanceSearch getBpelAdvanceSearchPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Content/bpel_AdvanceSearch",
                                       "bpel_AdvanceSearch_pt"), BpelAdvanceSearch.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BpelAdvanceSearch
     */
    @WebEndpoint(name = "bpel_AdvanceSearch_pt")
    public BpelAdvanceSearch getBpelAdvanceSearchPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Content/bpel_AdvanceSearch",
                                       "bpel_AdvanceSearch_pt"), BpelAdvanceSearch.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BPELADVANCESEARCHCLIENTEP_EXCEPTION != null) {
            throw BPELADVANCESEARCHCLIENTEP_EXCEPTION;
        }
        return BPELADVANCESEARCHCLIENTEP_WSDL_LOCATION;
    }

}
