<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="http://tempuri.org/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" name="AviancaService" targetNamespace="http://tempuri.org/">
    <wsdl:types>
        <xsd:schema targetNamespace="http://tempuri.org/Imports">
            <xsd:import schemaLocation="xsd0.xsd" namespace="http://tempuri.org/"/>
            <xsd:import schemaLocation="xsd1.xsd" namespace="http://schemas.microsoft.com/2003/10/Serialization/"/>
            <xsd:import schemaLocation="xsd2.xsd" namespace="http://schemas.datacontract.org/2004/07/AviancaDemoWcfService"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="IAviancaService_GetFlights_InputMessage">
        <wsdl:part name="parameters" element="tns:GetFlights"/>
    </wsdl:message>
    <wsdl:message name="IAviancaService_GetFlights_OutputMessage">
        <wsdl:part name="parameters" element="tns:GetFlightsResponse"/>
    </wsdl:message>
    <wsdl:portType name="IAviancaService">
        <wsdl:operation name="GetFlights">
            <wsdl:input wsaw:Action="http://tempuri.org/IAviancaService/GetFlights" message="tns:IAviancaService_GetFlights_InputMessage"/>
            <wsdl:output wsaw:Action="http://tempuri.org/IAviancaService/GetFlightsResponse" message="tns:IAviancaService_GetFlights_OutputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="BasicHttpBinding_IAviancaService" type="tns:IAviancaService">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="GetFlights">
            <soap:operation soapAction="http://tempuri.org/IAviancaService/GetFlights" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="AviancaService">
        <wsdl:port name="BasicHttpBinding_IAviancaService" binding="tns:BasicHttpBinding_IAviancaService">
            <soap:address location="http://www.javeriana.somee.com/AviancaService.svc"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>