
package co.edu.javeriana.proxies.updateestadoentrevista.proxy;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "bpel_updateobsestentrevista_client_ep",
                  targetNamespace =
                  "http://xmlns.oracle.com/app_eaes_soaint/SOA_Database_2/bpel_updateobsestentrevista",
                  wsdlLocation =
                  "http://bpm-dv1:7003/soa-infra/services/default/SOA_Database_2/bpel_updateobsestentrevista_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fapp_eaes_soaint%2FSOA_Database_2%2Fbpel_updateobsestentrevista%7Dbpel_updateobsestentrevista_client_ep")
@HandlerChain(file="Bpel_updateobsestentrevista_client_epProxy-HandlerChain.xml")
public class BpelUpdateobsestentrevistaClientEp extends Service {

    private final static URL BPELUPDATEOBSESTENTREVISTACLIENTEP_WSDL_LOCATION;
    private final static WebServiceException BPELUPDATEOBSESTENTREVISTACLIENTEP_EXCEPTION;
    private final static QName BPELUPDATEOBSESTENTREVISTACLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Database_2/bpel_updateobsestentrevista",
                  "bpel_updateobsestentrevista_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://bpm-dv1:7003/soa-infra/services/default/SOA_Database_2/bpel_updateobsestentrevista_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fapp_eaes_soaint%2FSOA_Database_2%2Fbpel_updateobsestentrevista%7Dbpel_updateobsestentrevista_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BPELUPDATEOBSESTENTREVISTACLIENTEP_WSDL_LOCATION = url;
        BPELUPDATEOBSESTENTREVISTACLIENTEP_EXCEPTION = e;
    }

    public BpelUpdateobsestentrevistaClientEp() {
        super(__getWsdlLocation(), BPELUPDATEOBSESTENTREVISTACLIENTEP_QNAME);
    }

    public BpelUpdateobsestentrevistaClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), BPELUPDATEOBSESTENTREVISTACLIENTEP_QNAME, features);
    }

    public BpelUpdateobsestentrevistaClientEp(URL wsdlLocation) {
        super(wsdlLocation, BPELUPDATEOBSESTENTREVISTACLIENTEP_QNAME);
    }

    public BpelUpdateobsestentrevistaClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BPELUPDATEOBSESTENTREVISTACLIENTEP_QNAME, features);
    }

    public BpelUpdateobsestentrevistaClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BpelUpdateobsestentrevistaClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BpelUpdateobsestentrevista
     */
    @WebEndpoint(name = "bpel_updateobsestentrevista_pt")
    public BpelUpdateobsestentrevista getBpelUpdateobsestentrevistaPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Database_2/bpel_updateobsestentrevista",
                                       "bpel_updateobsestentrevista_pt"), BpelUpdateobsestentrevista.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BpelUpdateobsestentrevista
     */
    @WebEndpoint(name = "bpel_updateobsestentrevista_pt")
    public BpelUpdateobsestentrevista getBpelUpdateobsestentrevistaPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Database_2/bpel_updateobsestentrevista",
                                       "bpel_updateobsestentrevista_pt"), BpelUpdateobsestentrevista.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BPELUPDATEOBSESTENTREVISTACLIENTEP_EXCEPTION != null) {
            throw BPELUPDATEOBSESTENTREVISTACLIENTEP_EXCEPTION;
        }
        return BPELUPDATEOBSESTENTREVISTACLIENTEP_WSDL_LOCATION;
    }

}
