# -----------------------------------------------------------------------------
# - DOCKERFILE
# - AUTOR: Brian Suarez | Eduardo Franco | Jhon Celemin | Wilman Ortiz
# - FECHA: 06-Octubre-2020
# - DESCRIPCION: Docker-compose que permite la creacion del
# -              contenedor con el servicio de comandos y queries de campanias
# ------------------------------------------------------------------------------

version: '3.7'
services:
  campaigns-command-services:
    image: wortiz1027/campaigns-command-services:latest
    container_name: campaigns-command-services
    hostname: campaigns-command-services
    restart: always
    ports:
      - 8087:8087
      - 6087:6087
    environment:  
      - CONFIG_SERVER=http://10.39.1.85:9090
      - EUREKA_SERVER=http://10.39.1.85:9091/eureka
      - EUREKA_HOST=10.39.1.85
      - RABBITMQ_HOST=10.39.1.85
      - DB_CAMPAIGNS_COMMAND_HOST=10.39.1.130
    networks:
      - ntw_backend
  campaigns-query-services:
    image: wortiz1027/campaigns-query-services:latest
    container_name: campaigns-query-services
    hostname: campaigns-query-services
    restart: always
    ports:
      - 8088:8088
      - 6088:6088
    environment:  
      - CONFIG_SERVER=http://10.39.1.85:9090
      - EUREKA_SERVER=http://10.39.1.85:9091/eureka
      - EUREKA_HOST=10.39.1.85
      - RABBITMQ_HOST=10.39.1.85
      - DB_CAMPAIGNS_QUERY_HOST=10.39.1.130      
    networks:
      - ntw_backend
networks:
  ntw_backend:
    external: true