<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.javeriana.edu/edu/schemas/process/reclutamiento/v1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://xmlns.javeriana.edu.co/co/schemas/process/bpm/consultarCandidatosVacante/v1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/resources/BPM/SCHEMAs/ConsultarCandidatosVacante.xsd"/>
            <oracle-xsl-mapper:rootElement name="Candidatos" namespace="http://xmlns.javeriana.edu.co/co/schemas/process/bpm/consultarCandidatosVacante/v1.0"/>
            <oracle-xsl-mapper:param name="candidatos"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/resources/BPM/SCHEMAs/Misional/Misional.xsd"/>
            <oracle-xsl-mapper:rootElement name="Candidatos" namespace="http://xmlns.javeriana.edu/edu/schemas/process/reclutamiento/v1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [MON APR 06 02:38:16 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <xsl:if test="count (/ns0:Candidatos/ns0:CandidatosType ) > 0">
         <tns:Candidatos>
            <xsl:for-each select="/ns0:Candidatos/ns0:CandidatosType">
               <tns:Candidato>
                  <tns:correoElectronico>
                     <xsl:value-of select="ns0:email"/>
                  </tns:correoElectronico>
                  <tns:resultado>
                     <xsl:value-of select="ns0:estado"/>
                  </tns:resultado>
               </tns:Candidato>
            </xsl:for-each>
         </tns:Candidatos>
      </xsl:if>
   </xsl:template>
</xsl:stylesheet>
