
package co.edu.javeriana.proxies.getfile.proxy;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "bpel_getfile_client_ep",
                  targetNamespace = "http://xmlns.oracle.com/app_eaes_soaint/SOA_Content/bpel_GetFile",
                  wsdlLocation =
                  "http://bpm-dv1:7003/soa-infra/services/default/SOA_Content/bpel_getfile_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fapp_eaes_soaint%2FSOA_Content%2Fbpel_GetFile%7Dbpel_getfile_client_ep")
@HandlerChain(file="Bpel_getfile_client_epProxy-HandlerChain.xml")
public class BpelGetfileClientEp extends Service {

    private final static URL BPELGETFILECLIENTEP_WSDL_LOCATION;
    private final static WebServiceException BPELGETFILECLIENTEP_EXCEPTION;
    private final static QName BPELGETFILECLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Content/bpel_GetFile", "bpel_getfile_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://bpm-dv1:7003/soa-infra/services/default/SOA_Content/bpel_getfile_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2Fapp_eaes_soaint%2FSOA_Content%2Fbpel_GetFile%7Dbpel_getfile_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BPELGETFILECLIENTEP_WSDL_LOCATION = url;
        BPELGETFILECLIENTEP_EXCEPTION = e;
    }

    public BpelGetfileClientEp() {
        super(__getWsdlLocation(), BPELGETFILECLIENTEP_QNAME);
    }

    public BpelGetfileClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), BPELGETFILECLIENTEP_QNAME, features);
    }

    public BpelGetfileClientEp(URL wsdlLocation) {
        super(wsdlLocation, BPELGETFILECLIENTEP_QNAME);
    }

    public BpelGetfileClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BPELGETFILECLIENTEP_QNAME, features);
    }

    public BpelGetfileClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BpelGetfileClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BpelGetFile
     */
    @WebEndpoint(name = "bpel_GetFile_pt")
    public BpelGetFile getBpelGetFilePt() {
        return super.getPort(new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Content/bpel_GetFile",
                                       "bpel_GetFile_pt"), BpelGetFile.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BpelGetFile
     */
    @WebEndpoint(name = "bpel_GetFile_pt")
    public BpelGetFile getBpelGetFilePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/app_eaes_soaint/SOA_Content/bpel_GetFile",
                                       "bpel_GetFile_pt"), BpelGetFile.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BPELGETFILECLIENTEP_EXCEPTION != null) {
            throw BPELGETFILECLIENTEP_EXCEPTION;
        }
        return BPELGETFILECLIENTEP_WSDL_LOCATION;
    }

}
