<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.javeriana.edu.co/co/schemas/process/bpm/WCC_Checkin/v1.0" xmlns:tns="http://www.stellent.com/CheckIn/" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://xmlns.oracle.com/app_eaes_soaint/SOA_Content/bpel_checkin_wcc"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpel_checkin_wcc.wsdl"/>
            <oracle-xsl-mapper:rootElement name="input" namespace="http://xmlns.javeriana.edu.co/co/schemas/process/bpm/WCC_Checkin/v1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/resources/SOA/WSDLs/CheckIn.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CheckInUniversal" namespace="http://www.stellent.com/CheckIn/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [FRI APR 03 22:39:58 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:CheckInUniversal>
         <tns:dDocName>
            <xsl:value-of select="/ns0:input/ns0:dDocName"/>
         </tns:dDocName>
         <tns:dDocTitle>
            <xsl:value-of select="/ns0:input/ns0:titulo"/>
         </tns:dDocTitle>
         <tns:dDocType>
            <xsl:value-of select="/ns0:input/ns0:tipo"/>
         </tns:dDocType>
         <tns:dDocAuthor>
            <xsl:value-of select="/ns0:input/ns0:autor"/>
         </tns:dDocAuthor>
         <tns:dSecurityGroup>
            <xsl:value-of select="/ns0:input/ns0:grupoSeguridad"/>
         </tns:dSecurityGroup>
         <tns:dDocAccount>
            <xsl:value-of select="/ns0:input/ns0:cuenta"/>
         </tns:dDocAccount>
         <tns:CustomDocMetaData>
            <xsl:if test="count (/ns0:input/ns0:customDocMetaData ) > 0">
               <xsl:for-each select="/ns0:input/ns0:customDocMetaData">
                  <tns:property>
                     <tns:name>
                        <xsl:value-of select="ns0:name"/>
                     </tns:name>
                     <tns:value>
                        <xsl:value-of select="ns0:value"/>
                     </tns:value>
                  </tns:property>
               </xsl:for-each>
            </xsl:if>
         </tns:CustomDocMetaData>
         <tns:primaryFile>
            <tns:fileName>
               <xsl:value-of select="/ns0:input/ns0:archivoPrimario/ns0:nombreArchivo"/>
            </tns:fileName>
            <tns:fileContent>
               <xsl:value-of select="/ns0:input/ns0:archivoPrimario/ns0:contenidoArchivo"/>
            </tns:fileContent>
         </tns:primaryFile>
      </tns:CheckInUniversal>
   </xsl:template>
</xsl:stylesheet>
