<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.javeriana.edu.co/co/schemas/process/bpm/WCC_GetFile/v1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:tns="http://www.stellent.com/GetFile/" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://xmlns.oracle.com/app_eaes_soaint/SOA_Content/bpel_GetFile"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/bpel_GetFile.wsdl"/>
            <oracle-xsl-mapper:rootElement name="input" namespace="http://xmlns.javeriana.edu.co/co/schemas/process/bpm/WCC_GetFile/v1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/resources/SOA/WSDLs/GetFile.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetFileByID" namespace="http://www.stellent.com/GetFile/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [SAT APR 04 11:14:24 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:GetFileByID>
         <tns:dID>
            <xsl:value-of select="/ns0:input/ns0:dID"/>
         </tns:dID>
         <tns:rendition>
            <xsl:value-of select="/ns0:input/ns0:tipoArchivo"/>
         </tns:rendition>
         <tns:extraProps>
            <xsl:if test="count (/ns0:input/ns0:extraProperty ) > 0">
               <xsl:for-each select="/ns0:input/ns0:extraProperty">
                  <tns:property>
                     <tns:name>
                        <xsl:value-of select="ns0:name"/>
                     </tns:name>
                     <tns:value>
                        <xsl:value-of select="ns0:value"/>
                     </tns:value>
                  </tns:property>
               </xsl:for-each>
            </xsl:if>
         </tns:extraProps>
      </tns:GetFileByID>
   </xsl:template>
</xsl:stylesheet>
