# -------------------------------------------------------------------
# - DOCKER COMPOSE FILE
# - AUTOR: Equipo 5
# - FECHA: 23-Octubre-2020
# - DESCRIPCION: Docker compose file que permite la
# -              creacion del contenedor para consultar la pasarela
# -------------------------------------------------------------------

version: '3.7'

services:
  paywoaint-query-service:
    image: paywoaint-query-service
    container_name: paywoaint-query-service
    hostname: paywoaint-query-service
    restart: always
    ports:
      - 8097:8097
    networks:
      - ntw_backend
    environment:
      - PAYWOAINT_HOST=paywoaint-service
      - PAYWOAINT_PORT=7075

networks:
  ntw_backend:
    external: true