
package co.edu.javeriana.proxies.insertarentrevista.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import co.edu.javeriana.proxies.insertarentrevista.types.InsertarEntrevistaType;
import co.edu.javeriana.proxies.insertarentrevista.types.ObjectFactory;
import co.edu.javeriana.proxies.insertarentrevista.types.ResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "bpel_insertarentrevista",
            targetNamespace = "http://xmlns.oracle.com/app_eaes_soaint/SOA_Database_2/bpel_insertarentrevista")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface BpelInsertarentrevista {


    /**
     *
     * @param payload
     * @return
     *     returns co.edu.javeriana.proxies.insertarentrevista.types.ResponseType
     */
    @WebMethod(action = "process")
    @WebResult(name = "response",
               targetNamespace = "http://xmlns.javeriana.edu.co/co/schemas/process/bpm/InsertarEntrevista/v1.0",
               partName = "payload")
    public ResponseType process(@WebParam(name = "request",
                                          targetNamespace =
                                          "http://xmlns.javeriana.edu.co/co/schemas/process/bpm/InsertarEntrevista/v1.0",
                                          partName = "payload") InsertarEntrevistaType payload);

}
