package co.edu.javeriana.proxies.insertarentrevista.proxy;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914
public class bpel_insertarentrevista_ptClient {
    public static void main(String[] args) {
        BpelInsertarentrevistaClientEp bpelInsertarentrevistaClientEp = new BpelInsertarentrevistaClientEp();
        BpelInsertarentrevista bpelInsertarentrevista = bpelInsertarentrevistaClientEp.getBpelInsertarentrevistaPt();
        // Add your code to call the desired methods.


    }
}
