//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 09:39:10 PM IST 
//


package us.com.service.aa.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.howtodoinjava.xml.school package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.howtodoinjava.xml.school
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetFlightsResponse }
     */
    public GetFlightsResponse createGetFlightsResponse() {
        return new GetFlightsResponse();
    }

    /**
     * Create an instance of {@link Flight }
     */
    public Flight createFlight() {
        return new Flight();
    }

    /**
     * Create an instance of {@link Information }
     */
    public Information createInformation() {
        return new Information();
    }

    /**
     * Create an instance of {@link Seat }
     */
    public Seat createSeat() {
        return new Seat();
    }

    /**
     * Create an instance of {@link SeatsList }
     */
    public SeatsList createSeatsList() {
        return new SeatsList();
    }

    /**
     * Create an instance of {@link GetFlightsRequest }
     */
    public GetFlightsRequest createGetFlightsRequest() {
        return new GetFlightsRequest();
    }

    /**
     * Create an instance of {@link GetAllFlightsRequest }
     */
    public GetAllFlightsRequest createGetAllFlightsRequest() {
        return new GetAllFlightsRequest();
    }

    /**
     * Create an instance of {@link GetAllFlightsResponse }
     */
    public GetAllFlightsResponse createGetAllFlightsResponse() {
        return new GetAllFlightsResponse();
    }

    /**
     * Create an instance of {@link Flights }
     */
    public Flights createFlights() {
        return new Flights();
    }

    /**
     * Create an instance of {@link InformationFlights }
     */
    public InformationFlights createInformationFlights() {
        return new InformationFlights();
    }

}
