# -----------------------------------------------------------------------------
# - DOCKERFILE
# - AUTOR: Wilman Ortiz
# - FECHA: 10-01-2022
# - DESCRIPCION: Docker-compose que permite la creacion del
# -              contenedor con el servicio de employees
# - COMMANDS:
# -     $ > docker-compose --env-file ./config/.env.dev config
# -     $ > docker-compose --env-file ./config/.env.dev up
# - DOCUMENTATION: https://docs.docker.com/compose/environment-variables/
# ------------------------------------------------------------------------------

version: '3.9'
services:
  employee-services:
    image: wortiz1027/employee-services:v1.0.5-20220117180152
    container_name: employee-services
    hostname: employee-services
    restart: always
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - SPRING_PROFILES_ACTIVE=${KEY_SPRING_PROFILES_ACTIVE}
      - DB_EMPLOYEES_CONNECTION=${KEY_DB_EMPLOYEES_CONNECTION}
      - DB_EMPLOYEES_NAME=${KEY_DB_EMPLOYEES_NAME}
      - DB_EMPLOYEES_USERNAME=${KEY_DB_EMPLOYEES_USERNAME}
      - DB_EMPLOYEES_PASSWORD=${KEY_DB_EMPLOYEES_PASSWORD}
      - APP_FILESYSTEM=${KEY_APP_FILESYSTEM}
      - KEYCLOAK_URL_BASE_CONNECTION=${KEY_KEYCLOAK_URL_BASE_CONNECTION}
      - KEYCLOAK_REALM=${KEY_KEYCLOAK_REALM}
      - KEYCLOAK_RESOURCE=${KEY_KEYCLOAK_RESOURCE}
      - KEYCLOAK_RESOURCE_SECRET=${KEY_KEYCLOAK_RESOURCE_SECRET}
    networks:
      - ntw_development
networks:
  ntw_development:
    external: true